# OLA WAHBA
# GO_STP_6027
# Prediction using Logistic Regression
# TASK 9 - Goeduhub Technologies


Predict retention of an employee within an organization such that whether the employee will leave the company or continue with it. An organization is only as good as its employees, and these people are the true source of its competitive advantage. Dataset is downloaded from Kaggle. Link: https://www.kaggle.com/giripujar/hr-analytics

First do data exploration and visualization, after this create a logistic regression model to predict Employee Attrition Using Machine Learning & Python. 

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [ ]:
df= pd.read_csv('/content/HR_comma_sep.csv')
df.head()

satisfaction_level  last_evaluation  ...  Department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

In [ ]:
df.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Department', 'salary'],
      dtype='object')

In [ ]:
df['left'].unique()

array([1, 0])

In [ ]:
df['Department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [ ]:
df.describe()

satisfaction_level  last_evaluation  ...          left  promotion_last_5years
count        14999.000000     14999.000000  ...  14999.000000           14999.000000
mean             0.612834         0.716102  ...      0.238083               0.021268
std              0.248631         0.171169  ...      0.425924               0.144281
min              0.090000         0.360000  ...      0.000000               0.000000
25%              0.440000         0.560000  ...      0.000000               0.000000
50%              0.640000         0.720000  ...      0.000000               0.000000
75%              0.820000         0.870000  ...      0.000000               0.000000
max              1.000000         1.000000  ...      1.000000               1.000000

[8 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   Department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [ ]:
df.shape

(14999, 10)

In [ ]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [ ]:
df.corr()

satisfaction_level  ...  promotion_last_5years
satisfaction_level               1.000000  ...               0.025605
last_evaluation                  0.105021  ...              -0.008684
number_project                  -0.142970  ...              -0.006064
average_montly_hours            -0.020048  ...              -0.003544
time_spend_company              -0.100866  ...               0.067433
Work_accident                    0.058697  ...               0.039245
left                            -0.388375  ...              -0.061788
promotion_last_5years            0.025605  ...               1.000000

[8 rows x 8 columns]

In [ ]:
df.min()

satisfaction_level       0.09
last_evaluation          0.36
number_project              2
average_montly_hours       96
time_spend_company          2
Work_accident               0
left                        0
promotion_last_5years       0
Department                 IT
salary                   high
dtype: object

In [ ]:
df.max()

satisfaction_level               1
last_evaluation                  1
number_project                   7
average_montly_hours           310
time_spend_company              10
Work_accident                    1
left                             1
promotion_last_5years            1
Department               technical
salary                      medium
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df.Department=lb.fit_transform(df.Department)
df.Department.unique()


array([7, 2, 3, 9, 8, 4, 0, 6, 5, 1])

In [ ]:
df['salary']=lb.fit_transform(df['salary'])
df['salary'].unique()

array([1, 2, 0])

In [ ]:
df.head()

satisfaction_level  last_evaluation  ...  Department  salary
0                0.38             0.53  ...           7       1
1                0.80             0.86  ...           7       2
2                0.11             0.88  ...           7       2
3                0.72             0.87  ...           7       1
4                0.37             0.52  ...           7       1

[5 rows x 10 columns]

In [ ]:
X=df.drop(['left'],axis='columns')
Y=df['left']

In [ ]:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=1)

In [ ]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_predict=model.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 1, 0])

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(y_test,y_predict)

0.7634343434343435

0.7634343434343435

In [ ]:
confusion_matrix(y_test,y_predict)

array([[3450,  306],
       [ 865,  329]])

array([[3450,  306],
       [ 865,  329]])

In [ ]:
dfp=pd.DataFrame({'Actual': y_test, 'Predicted': y_predict})
dfp

Actual  Predicted
11908       0          0
10508       0          0
9193        0          0
13087       0          0
506         1          0
...       ...        ...
250         1          0
5655        0          1
5377        0          0
3456        0          1
2406        0          0

[4950 rows x 2 columns]