# OLA WAHBA 
# Task 4 - Goeduhub Technologies
# ID : GO_STP_6027

**1-Import the numpy package under the name np and Print the numpy version and the configuration **

In [2]:
import numpy as np
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


***2. Create a null vector of size 10***

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

***3-Create Simple 1-D array and check type and check data types in array***

In [7]:
arr=np.arange(0,10)

print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***4-How to find number of dimensions, bytes per element and bytes of memory used?***

In [15]:
arr1=np.arange(0,10)
arr1.ndim


1

In [16]:
arr1.itemsize


8

In [17]:
arr1.nbytes

80

***5-Create a null vector of size 10 but the fifth value which is 1***

In [21]:
arr2=np.zeros(10)
arr2[4]=1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

***Create a vector with values ranging from 10 to 49***


In [23]:
arr3=np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

***7-Reverse a vector (first element becomes last)***


In [29]:
arrev=arr3[::-1]
arrev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [37]:
rev=np.flip(arr)
rev

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

***8-Create a 3x3 matrix with values ranging from 0 to 8***


In [42]:
arr4=np.arange(0,9)
p=arr4.reshape(3,3)
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

***9-Find indices of non-zero elements from [1,2,0,0,4,0]***

In [48]:
A=np.array([1,2,0,0,4,0])

z=np.nonzero(A)
z

(array([0, 1, 4]),)

***10-Create a 3x3 identity matrix***


In [53]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
d=np.eye(3,3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***11-Create a 3x3x3 array with random values***


In [71]:
r=np.random.random((3,3))
r

array([[0.32216556, 0.02206353, 0.3635429 ],
       [0.70131431, 0.23492724, 0.51907426],
       [0.62045327, 0.98626011, 0.96770798]])

***12-Create a 10x10 array with random values and find the minimum and maximum values***


In [67]:
s=np.random.random((10,10))
s

array([[0.5775895 , 0.38662853, 0.56638653, 0.27392847, 0.00621629,
        0.00423118, 0.19343311, 0.25531923, 0.67893626, 0.54268737],
       [0.35740335, 0.58667667, 0.93904072, 0.85297036, 0.98816512,
        0.41901216, 0.06343317, 0.56471165, 0.15152954, 0.91720139],
       [0.88659411, 0.52766993, 0.70107792, 0.17050889, 0.51943228,
        0.94892112, 0.26294779, 0.12116428, 0.78419629, 0.67722561],
       [0.31257068, 0.68450647, 0.22122368, 0.56725892, 0.65977957,
        0.9262419 , 0.92590586, 0.11715573, 0.19241918, 0.62378797],
       [0.98593395, 0.08622317, 0.11079922, 0.39443806, 0.10442266,
        0.42835142, 0.32072396, 0.89136802, 0.73804783, 0.2580948 ],
       [0.46005584, 0.75392478, 0.4570348 , 0.36150055, 0.67713767,
        0.34385542, 0.37463916, 0.89405234, 0.67571626, 0.21587999],
       [0.64734018, 0.723688  , 0.83789046, 0.75698693, 0.46650247,
        0.85082588, 0.70008246, 0.79742706, 0.67202086, 0.68298976],
       [0.82172787, 0.46801142, 0.7990021

In [68]:
s.min()

0.004231180821069325

In [69]:
s.max()

0.9881651223320574

***13-Create a random vector of size 30 and find the mean value***


In [75]:
v=np.random.random((3,10))
v

array([[0.67711931, 0.17607516, 0.40230014, 0.00505157, 0.87839282,
        0.20821011, 0.87962123, 0.10558769, 0.48330611, 0.76002249],
       [0.60440938, 0.59078777, 0.98492525, 0.13998581, 0.05246641,
        0.02056254, 0.57283598, 0.78903881, 0.61298329, 0.10804662],
       [0.11665115, 0.16988411, 0.71814942, 0.23354057, 0.92831806,
        0.80392811, 0.43803517, 0.9457256 , 0.29726209, 0.16704687]])

In [76]:
np.mean(v)

0.46234232133431913

***14-Create a 2d array with 1 on the border and 0 inside***


In [81]:
h=np.ones((5,5))
h[1:4,1:4]=0
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

***16-How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?***
Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20




In [97]:
w=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
w


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [99]:
w[1,5]


13

In [100]:
w[:1,]

array([[1, 2, 3, 4, 5, 6, 7]])

In [103]:
w[:,2]

array([ 3, 10])

In [105]:
w[0,1::2]

array([2, 4, 6])

In [106]:
w[1,5]=20
w

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

***17-How to Convert a 1D array to a 2D array with 2 rows***



In [109]:
n=np.arange(10)
n.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

***18-Create the following pattern without hardcoding. Use only numpy functions and the below input array a.***
a = np.array([1,2,3])`




In [114]:
a = np.array([1,2,3])
np.append(np.repeat(a,3),np.tile(a,3))


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

array([1, 1, 1, 2, 2, 2, 3, 3, 3])